### ISSUE TITLE
Fails due to old API spec kubeadm.yaml

### ISSUE THREAD

**Issue by kroy-the-rabbit** [gandazgul/k8s-infrastructure#24]
```
$ sudo kubeadm init --config=./kubeadm.yaml


your configuration file uses an old API spec: "kubeadm.k8s.io/v1alpha2". Please use kubeadm v1.12 instead and run 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
```

**Comment by gandazgul** [comment]
@kroy-the-rabbit thanks for reporting this!

I just opened a PR #22 that among other things fixes this. Please take a look.

**Comment by kroy-the-rabbit** [comment]
Great!  Were you going to merge that soon?

**Comment by rafaelgil83** [comment]
@kroy-the-rabbit I just merged. LMK if it's working now for you.

**Comment by kroy-the-rabbit** [comment]
Thanks.  Fixes it.  I'd probably mention in the documentation that it's necessary to modify `kubeadm.yaml` and changes the `advertiseAddress` for the API endpoint and `name` for the node registration before running the 2nd script.

Thanks again!

**Comment by gandazgul** [comment]
I just realized this. I'm booting up a VM with Fedora to try it out, see if I hit the other issue with docker as well. Kubeadm shouldn't need that IP address in there. I'll make a PR today.
